name: Integration tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
          extensions: intl
      - run: composer install
      - run: composer lint
      - run: composer test
